### ISSUE TITLE
Some items don't compress in Bulk Cell

### ISSUE THREAD

**Issue by dwyps** [62832/MEGACells#104]
In ATM9 when trying to put Enderium, Lumium and Signalum, from AllTheOres 2.2.3, in a Bulk Storage Cell with a compression enabled does not work and it just stays in ingots while there a recipes for blocks and also the nuggets can't be put into the cell either.
Not sure if some other items are affected by this, but right now it seems this is the only one I found that has the recipes, but can't be compressed or decompressed.

<img width="295" alt="image" src="https://github.com/62832/MEGACells/assets/59701536/bf667fa0-e80f-4815-ab84-b5d6cce114bc">
<img width="321" alt="image" src="https://github.com/62832/MEGACells/assets/59701536/f04cd2f2-e84f-495c-b3da-ef27a6043e1a">

**Comment by lolwew** [comment]
got same problem on ATM 9 No gregtech version: uranium, tin, lead, osmium, nickel all of those will only do block x1-9, it won't process ingots or nuggets.

**Comment by lolwew** [comment]
I'd guess ore unification deleted/modified the nugget, ingot item/recipe after mega cell initialized all compression recipes, since I got block x1-9 working normally, but ingot/nugget behaves like they can't compress at all

**Comment by 62832** [comment]
This should be fixed for the time being in the latest 2.3.5 release.

**Comment by TheOddball** [comment]
Rather than create a new issue for the same problem - It appears Niter from Thermal Series does not compress either.

**Comment by 62832** [comment]
There isn't much I can really do to cover every single edge case like this.

The main reason why these recipes from Thermal aren't working is because they aren't *technically* valid compression recipes, i.e. they don't use the same ingredient in each of the 4/9 slots. Thermal instead has the middle ingredient use a different key altogether and correspond to only the mod-specific resource instead of the general Forge tag for it, which makes it fail the compressibility check.

I've briefly discussed with the maintainer(s) of AlmostUnified about the possibility of sanitising ingredient keys post-unification, but as far as I understood it this isn't a priority at the moment. Until then, I would simply advise taking it up with your pack maintainers and asking them to explicitly change the recipe such that it would be supported.

**Comment by 62832** [comment]
Alternatively, consider using the `megacells:compression_overrides` tag and adding entries to it for items you want to be compressed regardless of the check.

**Comment by TheOddball** [comment]
Thank you for the full response. That is definitely strange how Thermal has those recipes. I am the pack maintainer, so I will fix it on my end. Thank you :)
