### ISSUE TITLE
[Feature Request]  Better decompression

### ISSUE THREAD

**Issue by 3453890470** [62832/MEGACells#126]
Is 4x decompression and 9x decompression performed in ae2 at the same time, because GTM has small dust and small pile dust, it seems that only small dust and dust decompression can be performed at present.

**Comment by 3453890470** [comment]
Also, whether you can make decompression support this mod
https://github.com/GregTech-Exploring-Pioneer/BiggerAE2

**Comment by 3453890470** [comment]
This mod also has a large single item storage, but this mod also supports storage fluids and FE, but I also like your decompression feature.

**Comment by 62832** [comment]
It would unfortunately not be possible to have them both done at the same time due to the way the system works by generating single "chains" of recipes. It would take a lot of reworking to have anything along the lines of "trees" for situations where both a 4x and 9x compression recipe may be available.

**Comment by 3453890470** [comment]
bad
