### ISSUE TITLE
Support for Modern industrialization metals for bulk compression.

### ISSUE THREAD

**Issue by xtended2l** [62832/MEGACells#154]
Please add support for MI metals i.e. antimony, stainless steel, titanium, etc.

**Comment by 62832** [comment]
This depends entirely on the recipes used by Modern Industrialisation, which I'm not in control of. You can also manually add all these metals yourself to the `#megacells:compression_overrides` tag via a datapack if there's something unusual about the recipes, assuming no other problems arise when doing so.

**Comment by xtended2l** [comment]
Are you sure? These are simple metals, which use default "9 nugget -> ingot", "9 Ingots -> Block" recipes. Drawers convert all these metals just fine.
Moreover bulk cell converts some of them - Coke, Lignite coal and Tungsten converts just great, that's why it is weird.

**Comment by 62832** [comment]
Are there any overrides already specified by things like your drawer mod? Without any information on which drawer mod you're using, that tells me nothing.

Besides, I had word earlier in the day that the recipes for metals in MI are indeed non-standard and as such won't be automatically picked up by bulk compression due to the criteria it's designed to look for in recipes.

**Comment by xtended2l** [comment]
I play ATM10 modpack. And there is Functional Storage mod, I mean compacting drawers from this mod.

**Comment by 62832** [comment]
Turns out I have been able to make a good few adjustments to the compression system to be able to catch some more odd cases, including the recipes for Modern Industrialization. This should make its way into the next release build.

**Comment by xtended2l** [comment]
Wow, great! :) Thank you and happy holidays!
