### ISSUE TITLE
Dismantling 1m Storage cells does not give Storage component

### ISSUE THREAD

**Issue by Sakreton** [62832/MEGACells#29]
It only gives the Housing but not the component
Running MEGA version 1.5.3

**Comment by 62832** [comment]
Forge or Fabric? I might have an idea of what's causing it, but I can't guarantee a hotfix just yet since the mod is undergoing a rather extensive rewrite and feature set implementation.

**Comment by Sakreton** [comment]
Forge, take your time ^^

Since i already know whats hopefully coming in the future i will gladly wait :P

**Comment by 62832** [comment]
Reopening until MEGA 2.0.0 is actually released to include the hotfix for this.

**Comment by 62832** [comment]
Fixed in 2.0.0-beta.0. If I'm misremembering let me know ASAP.

**Comment by James103** [comment]
I'm getting the same issue on Fabric, where dismantling a storage cell by right-clicking it voids the storage component inside. I'm running MEGA Cells 1.5.3 on Minecraft 1.19.2.

There are no later versions for Fabric, as all later versions that have the bugfix are Forge only. Is there any chance of a patch release containing the fix for Fabric before the full 2.0.0 release?
