### ISSUE TITLE
Autocrafting missing ingredients when using compression upgrade

### ISSUE THREAD

**Issue by bemerged** [62832/MEGACells#42]
I moved all my cobblestone to a bulk item disk with compression enabled.

![grafik](https://user-images.githubusercontent.com/29038515/215342006-3a474d9d-7af3-4215-967e-9d825e7332aa.png)

It is compressing all stages and I am able to extract a stack of usual cobblestone manually, even though the terminal tells me, that only 5 are available. 

![grafik](https://user-images.githubusercontent.com/29038515/215342051-125dc4e8-536a-4adf-a18e-d771c1bff1ec.png)

Problems occur, when you try to autocraft something, that needs cobblestone.

![grafik](https://user-images.githubusercontent.com/29038515/215342149-57ec853f-8931-4a9b-886f-f4571c73e995.png)

I can't order this craft, because of partially missing ingredients, but they are not indicated. (All other items are in stock and craft works, when supply cobblestone on a different way)

**Comment by 62832** [comment]
For the time being there isn't much I can do aside from suggesting that you supply your own patterns for crafting down the required variants.

**Comment by bemerged** [comment]
I used compating drawers before, which handles this much better. When I have 18 redstone, the drawer exposes its content like "18 redstone, 2 redstone blocks" while still handling extraction well.

I mean, what is the reason for using the compression upgrade, if it doesn't allow direct access to all tiers? I could just use the general bulk storage and add compressing recipes.

**Comment by bemerged** [comment]
Alright keep it as a suggestion then. Right now the compression upgrade is pretty much useless when working this way:

1. We don't "safe bytes" when compressing, because it's a bulk cell anyways and still counts the lowest tier.
2. Right now it's just compressing up so we need recipes for uncompressing. Without the upgrade it would be the exact same thing just with recipes for compressing.
3. Now just adds overhead without providing any useful thing.

I think most of the people will agree, that if it doesn't work for autocrafting, there is no need to use it.

**Comment by Mecr0mage** [comment]
id argue that the compression card is quite useful even without a active decompression function in its storage, i think your understating just how much of a time and crafting operations save only having to decompress down instead of up is. i can think of quite a few use cases for this even if the upgrade only made it compress to the highest variant and then i just had crafting card ME interfaces hooked up to storage busses for player use storage and ofc the patterns for decompressing for autocrafting.

**Comment by RaVenInTheDark** [comment]
Could we consider some sort of block which offers decompression patterns for an amount of items? then again, manual decompression patterns would work fine..?

**Comment by bemerged** [comment]
You could also allow to set max/min compression levels. I'm playing ATM8 at the moment, where copression goes up to 9x. This mean I would need 10 patterns to go from Diamond Block x9 to Diamond which is stupid af.

**Comment by 62832** [comment]
Since I've been on an impromptu hiatus from modding and I realise I've failed to give much of an update on this one, I might as well describe what I hope to achieve at some point to fix this.

Similarly to what @RaVenInTheDark suggests, the idea is to have a "MEGA Decompression Module" cable part that enables this mechanic across the whole network it's attached to. This may use a grid service to query all available chests and drives on the network and see if they contain bulk cells upgraded with a compression card, from which it may gather what items need to be decompressed back down. This part may then both provide its own "fake patterns" and be able to carry out the crafting on its own, off-loading that responsibility from any existing auto-crafting infrastructure like molecular assembler towers.

Whether or not I can actually implement this in a reasonable time frame is uncertain due to personal circumstances. In any case, I leave that up for discussion to see if this would be the ideal solution for people, and by all means welcome any external contributions to help achieve this once and for all.
