### ISSUE TITLE
Suggestion: bulk cell compression supporting compressed-only blocks

### ISSUE THREAD

**Issue by DragonOfMath** [62832/MEGACells#58]
Currently in 1.19.2, items which can be compressed but not de-compressed, such as melon slices, amethyst shards, clay balls, and magma cream won't be compressed into blocks when added to a bulk cell with compression enabled. Additionally, they cannot be inserted into a bulk cell for the compressed blocks either.

It would be convenient to change this behavior in 1.19.2+ so that compression may work regardless if the block can be readily decompressed, as decompression is usually handled via either the dedicated module for it or by other crafting/processing means.

**Comment by 62832** [comment]
This was the intended behaviour initially to mimic the behaviour of a compacting drawer from drawer mods like Functional Storage, as the assumption was that the compression/decompression process should not be carried out on items for which the process was non-reversible.

That said, I'm open to giving this some more thought later down the line and seeing if maybe it would be worth allowing the inclusion of non-reversible recipes — if even possible — as an added bonus for the entry barrier of the compression feature.

**Comment by 62832** [comment]
I've only just been informed that Functional Storage [uses a tag](https://github.com/Buuz135/FunctionalStorage/blob/main/src/main/java/com/buuz135/functionalstorage/util/CompactingUtil.java#L86) to determine whether to ignore the reversibility check for a recipe in order to allow for things such as Nether quartz and melon slices to be compressed in drawers. With this in mind, it might be worth implementing the same system for use by the compression service as well, ideally prioritising FS's own tag if present in case existing configurations were made with that tag.

**Comment by 62832** [comment]
Reopening this as the current implementation of reversibility overrides turned out to be a bit of a disaster.
