### ISSUE TITLE
Bulk Item Compression is overriding patterns.

### ISSUE THREAD

**Issue by kalutro** [62832/MEGACells#87]
This may be intentional.

In ATM8, I am using the Bulk Item cell with the Compression card and the Decompression module to easily make the 5x- and 6x-compressed blocks I need. I also have Mystical Agriculture to make the base items. In my case, I am trying to make Obsidian 5x. When I try to craft Obsidian with a pattern using Obsidian Essence, instead it will just decompress the blocks I already have, and subsequently re-compress them.

This doesn't make sense to me. Is this intended?

**Comment by 62832** [comment]
This isn't to do with MEGA as much as it is to do with AE2 itself and the lack of something like a priority system for patterns.

Since you're using MA essence, the only thing I can suggest to you is that you passively craft all your essence into obsidian instead of using an on-demand craft for this.
