### ISSUE TITLE
Bulk cells work with level emitters

### ISSUE THREAD

**Issue by micrwvae** [62832/MEGACells#88]
i noticed in atm8 that level emitters dont read the 'correct' level of for example iron nuggets if the iron is stored in the bulk cells w compression enabled

not sure if its possible to make them read the actual amount but it would be a nice feature

**Comment by 62832** [comment]
Unfortunately this simply isn't possible due to how items are reported by bulk cell inventories and the fact that ME networks in general are not designed to keep track of _what_ storage medium an item might be on. You may need to come up with a solution involving some more complex redstone if you wish to keep track of the "full" amount of a lower compressed variant.
